# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ox < Formula
  desc "The hivemind for agentic engineering"
  homepage "https://sageox.ai"
  version "0.14.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sageox/ox/releases/download/v0.14.1/ox_0.14.1_darwin_amd64.tar.gz"
      sha256 "e7609b1657aae38d875f84ad922cabf63ba306b079fe5c2b9e5cf9cbac2ed930"

      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sageox/ox/releases/download/v0.14.1/ox_0.14.1_darwin_arm64.tar.gz"
      sha256 "008ba217639ff65211e4ac73a43b9b8790485a1329820fc4715da57889a3d8f0"

      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageox/ox/releases/download/v0.14.1/ox_0.14.1_linux_amd64.tar.gz"
      sha256 "775707de99e1454eabb41c9f7bb79d08dda350f3a2550fa02693a9f38cc01603"
      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageox/ox/releases/download/v0.14.1/ox_0.14.1_linux_arm64.tar.gz"
      sha256 "581d7995aff088e46e22c8c6990ba13e05670a8f7b46967415e79df38b0cf127"
      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
  end

  test do
    system "#{bin}/ox", "version"
  end
end
