# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ox < Formula
  desc "The hivemind for agentic engineering"
  homepage "https://sageox.ai"
  version "0.20.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sageox/ox/releases/download/v0.20.0/ox_0.20.0_darwin_amd64.tar.gz"
      sha256 "dcf9fdad4e9a57f6cb000e21e2d6f60574307c1bf2ce8c1c11356070e2230fa6"

      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sageox/ox/releases/download/v0.20.0/ox_0.20.0_darwin_arm64.tar.gz"
      sha256 "a95c690e760dd9197bb94d9e6b0358cf4db66fcb8e25f5bcfe56dd4009c79d65"

      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageox/ox/releases/download/v0.20.0/ox_0.20.0_linux_amd64.tar.gz"
      sha256 "bcc105ae5b857f5521f7db369eb1f9f7907c796e4734cef3e0bdb010a01a6831"
      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageox/ox/releases/download/v0.20.0/ox_0.20.0_linux_arm64.tar.gz"
      sha256 "b144cbb9baf80fcace778e0d58469234a46ce6b48317bd2346c2b1881d52dc45"
      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
  end

  test do
    system "#{bin}/ox", "version"
  end
end
