# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ox < Formula
  desc "The hivemind for agentic engineering"
  homepage "https://sageox.ai"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sageox/ox/releases/download/v0.18.0/ox_0.18.0_darwin_amd64.tar.gz"
      sha256 "2464eb6e0ff0a00293f1b7701c1c424948e0434fe064003183caf69f9abaa11c"

      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sageox/ox/releases/download/v0.18.0/ox_0.18.0_darwin_arm64.tar.gz"
      sha256 "d22ab22031add5d9ad424e970cec83bc186e1209b87607c9665f1d3fc5175de3"

      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageox/ox/releases/download/v0.18.0/ox_0.18.0_linux_amd64.tar.gz"
      sha256 "41ac7204465beee715ef47e2c6b61eb88f86199a1f2c4b5b12e6c9c53594db48"
      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageox/ox/releases/download/v0.18.0/ox_0.18.0_linux_arm64.tar.gz"
      sha256 "deb475eb73e76132fa6f435abed27e9a6c930191614854057e4573274d485d9f"
      define_method(:install) do
        bin.install "ox"
        bin.install "ox-adapter-claude-code"
        bin.install "ox-adapter-gemini"
        bin.install "ox-adapter-codex"
        bin.install "ox-adapter-amp"
        bin.install "ox-adapter-opencode"
        bin.install "ox-adapter-pi"
        bin.install "ox-adapter-omp"
        bin.install "ox-adapter-aider"
        bin.install "ox-adapter-droid"
        bin.install "ox-adapter-goose"
      end
    end
  end

  test do
    system "#{bin}/ox", "version"
  end
end
